Update anchore-enterprise.yaml

diff --git a/.github/workflows/anchore-enterprise.yaml b/.github/workflows/anchore-enterprise.yaml
--- a/.github/workflows/anchore-enterprise.yaml
+++ b/.github/workflows/anchore-enterprise.yaml
@@ -68,6 +68,8 @@ jobs:
         retention-days: 14
     - name: Pull Evaluation
       run: |
+        set -o pipefail
+        # we have to set pipefail so that we can still gate on the evaluation, otherwise piping into tee will mask the failure
         docker run -e ANCHORE_CLI_USER -e ANCHORE_CLI_PASS -e ANCHORE_CLI_URL anchore/engine-cli anchore-cli evaluate check --detail ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_SHA} | tee evaluation.txt
     - name: Archive Evaluation
       if: always()
@@ -76,10 +78,6 @@ jobs:
         name: evaluation-report
         path: evaluation.txt
         retention-days: 14
-    - name: Gate on Evaluation
-      run: |
-        docker run -e ANCHORE_CLI_USER -e ANCHORE_CLI_PASS -e ANCHORE_CLI_URL anchore/engine-cli anchore-cli evaluate check ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_SHA}
-
         
   Promote-Deploy:
     needs: Evaluate
